### ISSUE TITLE
目前看过存在的严重问题

### ISSUE THREAD

**Issue by Iamrookie** [hss01248/ImageLoader#10]
1.使用的view是imageview  或者bigImageview  （操作先加载出图片，按home键出去一会儿在点开app，有的手机会不崩溃，大部分手机有问题） 都会有bitmap 已经回收重新被使用的问题，导致崩溃，解决使用simpledraweeview 可以避过这个问题。

2.其次设置圆形边框的颜色和宽度不正常。

3.清除内存方法到最后方法是空的

4.算了，不知道写啥好了，作者都不在了......

**Comment by hss01248** [comment]
我来了...  fresco加载不要用普通imageview,很容易挂.之前试过去解决,搞不好

**Comment by hss01248** [comment]
1.fresco用普通imageview加载的问题解决了... 思路参考的是 https://juejin.im/post/5a5b53786fb9a01c9b65e949
2. 边框的设置只是写了空方法,并没有实现....
