### ISSUE TITLE
请教一下,当activity onPause()的时候,这些已加载的图片是如何释放的?

### ISSUE THREAD

**Issue by KaleXia** [hss01248/ImageLoader#3]
现在遇到问题是,我不停的开activity,会引起oom

**Comment by hss01248** [comment]
不会释放,activity都没有destory,view都还在window上,怎么可能会释放.
不停地开activity,就是只有一个textview,最终也会oom.你们这测试的思路不对.

**Comment by KaleXia** [comment]
啊.那我应该从哪方面着手解决这个问题呢

**Comment by hss01248** [comment]
activity的launchMode 设置为singletop
